<?php

class ScriptGenerator {
    
    /**
     * Generates the entire remediation script.
     */
    public function generateFullScript(array $diff, array $sourceSchema, array $targetSchema, string $targetDbName = 'TargetDatabase'): string {
        $date = date('Y-m-d H:i:s');
        
        $sql = [];
        $sql[] = "-- ==========================================================================";
        $sql[] = "-- Generated by SQL Schema Comparator";
        $sql[] = "-- Run Date: $date";
        $sql[] = "-- Target Database: [$targetDbName]";
        $sql[] = "-- WARNING: Always back up your database and review scripts before executing.";
        $sql[] = "-- ==========================================================================";
        $sql[] = "";
        $sql[] = "USE [" . str_replace(['[', ']'], '', $targetDbName) . "];";
        $sql[] = "GO";
        $sql[] = "";

        $drops = [];
        $creates = [];

        // 1. DROP extra constraints/indexes in target to clear way (or for mismatches)
        // Mismatches PKs
        foreach ($diff['mismatches']['primary_keys'] as $tableKey => $item) {
            $drops[] = $this->generateDropPrimaryKey($item['target']);
        }
        // Mismatches FKs
        foreach ($diff['mismatches']['foreign_keys'] as $fkKey => $item) {
            $drops[] = $this->generateDropForeignKey($item['target']);
        }
        // Mismatches Uniques
        foreach ($diff['mismatches']['unique_constraints'] as $ucKey => $item) {
            $drops[] = $this->generateDropUniqueConstraint($item['target']);
        }
        // Mismatches Checks
        foreach ($diff['mismatches']['check_constraints'] as $ccKey => $item) {
            $drops[] = $this->generateDropCheckConstraint($item['target']);
        }
        // Mismatches Defaults
        foreach ($diff['mismatches']['default_constraints'] as $dcKey => $item) {
            $drops[] = $this->generateDropDefaultConstraint($item['target']);
        }
        // Mismatches Indexes
        foreach ($diff['mismatches']['indexes'] as $idxKey => $item) {
            $drops[] = $this->generateDropIndex($item['target']);
        }
        // Mismatches Triggers
        foreach ($diff['mismatches']['triggers'] as $trgKey => $item) {
            $drops[] = $this->generateDropTrigger($item['target']);
        }
        // Mismatches Views
        foreach ($diff['mismatches']['views'] as $key => $item) {
            $drops[] = $this->generateDropView($item['target']);
        }
        // Mismatches Procedures
        foreach ($diff['mismatches']['procedures'] as $key => $item) {
            $drops[] = $this->generateDropProcedure($item['target']);
        }
        // Mismatches Functions
        foreach ($diff['mismatches']['functions'] as $key => $item) {
            $drops[] = $this->generateDropFunction($item['target']);
        }

        // Drop extra objects if configured
        // FKs
        foreach ($diff['missing_in_source']['foreign_keys'] as $fk) {
            $drops[] = "-- Target-only Foreign Key to drop\n" . $this->generateDropForeignKey($fk);
        }
        // PKs
        foreach ($diff['missing_in_source']['primary_keys'] as $pk) {
            $drops[] = "-- Target-only Primary Key to drop\n" . $this->generateDropPrimaryKey($pk);
        }
        // Unique
        foreach ($diff['missing_in_source']['unique_constraints'] as $uc) {
            $drops[] = "-- Target-only Unique Constraint to drop\n" . $this->generateDropUniqueConstraint($uc);
        }
        // Default
        foreach ($diff['missing_in_source']['default_constraints'] as $dc) {
            $drops[] = "-- Target-only Default Constraint to drop\n" . $this->generateDropDefaultConstraint($dc);
        }
        // Checks
        foreach ($diff['missing_in_source']['check_constraints'] as $cc) {
            $drops[] = "-- Target-only Check Constraint to drop\n" . $this->generateDropCheckConstraint($cc);
        }
        // Indexes
        foreach ($diff['missing_in_source']['indexes'] as $idx) {
            $drops[] = "-- Target-only Index to drop\n" . $this->generateDropIndex($idx);
        }
        // Triggers
        foreach ($diff['missing_in_source']['triggers'] as $trg) {
            $drops[] = "-- Target-only Trigger to drop\n" . $this->generateDropTrigger($trg);
        }
        // Views
        foreach ($diff['missing_in_source']['views'] as $view) {
            $drops[] = "-- Target-only View to drop\n" . $this->generateDropView($view);
        }
        // Procedures
        foreach ($diff['missing_in_source']['procedures'] as $proc) {
            $drops[] = "-- Target-only Procedure to drop\n" . $this->generateDropProcedure($proc);
        }
        // Functions
        foreach ($diff['missing_in_source']['functions'] as $func) {
            $drops[] = "-- Target-only Function to drop\n" . $this->generateDropFunction($func);
        }
        // Extra target-only columns (commented out by default for safety)
        foreach ($diff['missing_in_source']['columns'] as $col) {
            $drops[] = "-- WARNING: Column [{$col['name']}] in table [{$col['schema']}].[{$col['table']}] only exists in target. Uncomment to drop:";
            $drops[] = "-- ALTER TABLE [{$col['schema']}].[{$col['table']}] DROP COLUMN [{$col['name']}];\n-- GO";
        }
        // Extra target-only tables (commented out by default for safety)
        foreach ($diff['missing_in_source']['tables'] as $table) {
            $drops[] = "-- WARNING: Table [{$table['schema']}].[{$table['name']}] only exists in target. Uncomment to drop:";
            $drops[] = "-- DROP TABLE [{$table['schema']}].[{$table['name']}];\n-- GO";
        }

        // Add drops to main sql if not empty
        if (!empty($drops)) {
            $sql[] = "-- ==========================================================================";
            $sql[] = "-- 1. DROPS / CLEANUP";
            $sql[] = "-- ==========================================================================";
            $sql = array_merge($sql, array_filter($drops));
            $sql[] = "";
        }

        // 2. CREATES / ALTERS
        // Create Missing Tables
        if (!empty($diff['missing_in_target']['tables'])) {
            $creates[] = "-- ============================================== --";
            $creates[] = "-- CREATE MISSING TABLES                          --";
            $creates[] = "-- ============================================== --";
            foreach ($diff['missing_in_target']['tables'] as $key => $table) {
                $creates[] = $this->generateCreateTable($key, $table, $sourceSchema['columns']);
            }
        }

        // Add Missing Columns
        if (!empty($diff['missing_in_target']['columns'])) {
            $creates[] = "-- ============================================== --";
            $creates[] = "-- ADD MISSING COLUMNS                            --";
            $creates[] = "-- ============================================== --";
            foreach ($diff['missing_in_target']['columns'] as $col) {
                $creates[] = $this->generateAlterTableAddColumn($col);
            }
        }

        // Modify Column Mismatches
        if (!empty($diff['mismatches']['columns'])) {
            $creates[] = "-- ============================================== --";
            $creates[] = "-- MODIFY COLUMNS                                 --";
            $creates[] = "-- ============================================== --";
            foreach ($diff['mismatches']['columns'] as $item) {
                $creates[] = $this->generateAlterTableModifyColumn($item['source'], $item['target']);
            }
        }

        // Add Missing/Mismatched PKs
        $pksToAdd = array_merge(
            $diff['missing_in_target']['primary_keys'],
            array_map(fn($x) => $x['source'], $diff['mismatches']['primary_keys'])
        );
        if (!empty($pksToAdd)) {
            $creates[] = "-- ============================================== --";
            $creates[] = "-- PRIMARY KEYS                                   --";
            $creates[] = "-- ============================================== --";
            foreach ($pksToAdd as $pk) {
                $creates[] = $this->generateAddPrimaryKey($pk);
            }
        }

        // Add Missing/Mismatched Default Constraints
        $dcsToAdd = array_merge(
            $diff['missing_in_target']['default_constraints'],
            array_map(fn($x) => $x['source'], $diff['mismatches']['default_constraints'])
        );
        if (!empty($dcsToAdd)) {
            $creates[] = "-- ============================================== --";
            $creates[] = "-- DEFAULT CONSTRAINTS                            --";
            $creates[] = "-- ============================================== --";
            foreach ($dcsToAdd as $dc) {
                $creates[] = $this->generateAddDefaultConstraint($dc);
            }
        }

        // Add Missing/Mismatched Unique Constraints
        $ucsToAdd = array_merge(
            $diff['missing_in_target']['unique_constraints'],
            array_map(fn($x) => $x['source'], $diff['mismatches']['unique_constraints'])
        );
        if (!empty($ucsToAdd)) {
            $creates[] = "-- ============================================== --";
            $creates[] = "-- UNIQUE CONSTRAINTS                             --";
            $creates[] = "-- ============================================== --";
            foreach ($ucsToAdd as $uc) {
                $creates[] = $this->generateAddUniqueConstraint($uc);
            }
        }

        // Add Missing/Mismatched Check Constraints
        $ccsToAdd = array_merge(
            $diff['missing_in_target']['check_constraints'],
            array_map(fn($x) => $x['source'], $diff['mismatches']['check_constraints'])
        );
        if (!empty($ccsToAdd)) {
            $creates[] = "-- ============================================== --";
            $creates[] = "-- CHECK CONSTRAINTS                              --";
            $creates[] = "-- ============================================== --";
            foreach ($ccsToAdd as $cc) {
                $creates[] = $this->generateAddCheckConstraint($cc);
            }
        }

        // Add Missing/Mismatched Indexes
        $idxsToAdd = array_merge(
            $diff['missing_in_target']['indexes'],
            array_map(fn($x) => $x['source'], $diff['mismatches']['indexes'])
        );
        if (!empty($idxsToAdd)) {
            $creates[] = "-- ============================================== --";
            $creates[] = "-- INDEXES                                        --";
            $creates[] = "-- ============================================== --";
            foreach ($idxsToAdd as $idx) {
                $creates[] = $this->generateAddIndex($idx);
            }
        }

        // Add Missing/Mismatched Foreign Keys
        $fksToAdd = array_merge(
            $diff['missing_in_target']['foreign_keys'],
            array_map(fn($x) => $x['source'], $diff['mismatches']['foreign_keys'])
        );
        if (!empty($fksToAdd)) {
            $creates[] = "-- ============================================== --";
            $creates[] = "-- FOREIGN KEYS                                   --";
            $creates[] = "-- ============================================== --";
            foreach ($fksToAdd as $fk) {
                $creates[] = $this->generateAddForeignKey($fk);
            }
        }

        // Add Missing/Mismatched Triggers
        $trgsToAdd = array_merge(
            $diff['missing_in_target']['triggers'],
            array_map(fn($x) => $x['source'], $diff['mismatches']['triggers'])
        );
        if (!empty($trgsToAdd)) {
            $creates[] = "-- ============================================== --";
            $creates[] = "-- TRIGGERS                                       --";
            $creates[] = "-- ============================================== --";
            foreach ($trgsToAdd as $trg) {
                $creates[] = $this->generateAddTrigger($trg);
            }
        }

        // Add Missing/Mismatched Views
        $viewsToAdd = array_merge(
            $diff['missing_in_target']['views'] ?? [],
            array_map(fn($x) => $x['source'], $diff['mismatches']['views'] ?? [])
        );
        if (!empty($viewsToAdd)) {
            $creates[] = "-- ============================================== --";
            $creates[] = "-- VIEWS                                          --";
            $creates[] = "-- ============================================== --";
            foreach ($viewsToAdd as $view) {
                $creates[] = $this->generateAddView($view);
            }
        }

        // Add Missing/Mismatched Procedures
        $procsToAdd = array_merge(
            $diff['missing_in_target']['procedures'] ?? [],
            array_map(fn($x) => $x['source'], $diff['mismatches']['procedures'] ?? [])
        );
        if (!empty($procsToAdd)) {
            $creates[] = "-- ============================================== --";
            $creates[] = "-- PROCEDURES                                     --";
            $creates[] = "-- ============================================== --";
            foreach ($procsToAdd as $proc) {
                $creates[] = $this->generateAddProcedure($proc);
            }
        }

        // Add Missing/Mismatched Functions
        $funcsToAdd = array_merge(
            $diff['missing_in_target']['functions'] ?? [],
            array_map(fn($x) => $x['source'], $diff['mismatches']['functions'] ?? [])
        );
        if (!empty($funcsToAdd)) {
            $creates[] = "-- ============================================== --";
            $creates[] = "-- FUNCTIONS                                      --";
            $creates[] = "-- ============================================== --";
            foreach ($funcsToAdd as $func) {
                $creates[] = $this->generateAddFunction($func);
            }
        }

        if (!empty($creates)) {
            $sql[] = "-- ==========================================================================";
            $sql[] = "-- 2. CREATIONS / MODIFICATIONS";
            $sql[] = "-- ==========================================================================";
            $sql = array_merge($sql, array_filter($creates));
        }

        return implode("\n", $sql);
    }

    public function generateCreateTable(string $tableKey, array $table, array $allColumns): string {
        $schema = $table['schema'];
        $name = $table['name'];
        
        $colLines = [];
        foreach ($allColumns as $colKey => $col) {
            $colTableKey = strtolower($col['schema'] . '.' . $col['table']);
            if ($colTableKey === $tableKey) {
                $colLines[] = "    " . $this->getColumnSqlDefinition($col);
            }
        }
        
        $sql = "CREATE TABLE [$schema].[$name] (\n";
        $sql .= implode(",\n", $colLines);
        $sql .= "\n);\nGO";
        return $sql;
    }

    private function getColumnSqlDefinition(array $col): string {
        $def = "[" . $col['name'] . "] " . $col['type'];
        
        if ($col['length'] !== null) {
            $len = $col['length'] === -1 ? 'max' : $col['length'];
            $def .= "($len)";
        } elseif ($col['precision'] !== null && $col['scale'] !== null) {
            $def .= "(" . $col['precision'] . ", " . $col['scale'] . ")";
        }
        
        if ($col['nullable']) {
            $def .= " NULL";
        } else {
            $def .= " NOT NULL";
        }
        
        if ($col['column_default'] !== null) {
            $def .= " DEFAULT " . $col['column_default'];
        }
        
        return $def;
    }

    public function generateAlterTableAddColumn(array $col): string {
        $def = $this->getColumnSqlDefinition($col);
        return "ALTER TABLE [{$col['schema']}].[{$col['table']}] ADD $def;\nGO";
    }

    public function generateAlterTableModifyColumn(array $srcCol, array $tgtCol): string {
        // Build the basic ALTER COLUMN type modification
        $def = "[{$srcCol['name']}] {$srcCol['type']}";
        if ($srcCol['length'] !== null) {
            $len = $srcCol['length'] === -1 ? 'max' : $srcCol['length'];
            $def .= "($len)";
        } elseif ($srcCol['precision'] !== null && $srcCol['scale'] !== null) {
            $def .= "(" . $srcCol['precision'] . ", " . $srcCol['scale'] . ")";
        }
        
        if ($srcCol['nullable']) {
            $def .= " NULL";
        } else {
            $def .= " NOT NULL";
        }

        $sql = "ALTER TABLE [{$srcCol['schema']}].[{$srcCol['table']}] ALTER COLUMN $def;\nGO";
        return $sql;
    }

    public function generateAddPrimaryKey(array $pk): string {
        $cols = implode(', ', array_map(fn($c) => "[$c] ASC", $pk['columns']));
        return "ALTER TABLE [{$pk['schema']}].[{$pk['table']}] ADD CONSTRAINT [{$pk['name']}] PRIMARY KEY CLUSTERED ($cols);\nGO";
    }

    public function generateDropPrimaryKey(array $pk): string {
        return "ALTER TABLE [{$pk['schema']}].[{$pk['table']}] DROP CONSTRAINT [{$pk['name']}];\nGO";
    }

    public function generateAddForeignKey(array $fk): string {
        $cols = implode(', ', array_map(fn($c) => "[$c]", $fk['columns']));
        $refCols = implode(', ', array_map(fn($c) => "[$c]", $fk['ref_columns']));
        
        $sql = "ALTER TABLE [{$fk['schema']}].[{$fk['table']}] WITH CHECK ADD CONSTRAINT [{$fk['name']}] FOREIGN KEY ($cols)\n";
        $sql .= "REFERENCES [{$fk['ref_schema']}].[{$fk['ref_table']}] ($refCols)";
        
        $del = str_replace('_', ' ', $fk['on_delete']);
        $upd = str_replace('_', ' ', $fk['on_update']);
        
        if ($del !== 'NO ACTION') {
            $sql .= "\nON DELETE $del";
        }
        if ($upd !== 'NO ACTION') {
            $sql .= "\nON UPDATE $upd";
        }
        
        $sql .= ";\nALTER TABLE [{$fk['schema']}].[{$fk['table']}] CHECK CONSTRAINT [{$fk['name']}];\nGO";
        return $sql;
    }

    public function generateDropForeignKey(array $fk): string {
        return "ALTER TABLE [{$fk['schema']}].[{$fk['table']}] DROP CONSTRAINT [{$fk['name']}];\nGO";
    }

    public function generateAddUniqueConstraint(array $uc): string {
        $cols = implode(', ', array_map(fn($c) => "[$c]", $uc['columns']));
        return "ALTER TABLE [{$uc['schema']}].[{$uc['table']}] ADD CONSTRAINT [{$uc['name']}] UNIQUE NONCLUSTERED ($cols);\nGO";
    }

    public function generateDropUniqueConstraint(array $uc): string {
        return "ALTER TABLE [{$uc['schema']}].[{$uc['table']}] DROP CONSTRAINT [{$uc['name']}];\nGO";
    }

    public function generateAddCheckConstraint(array $cc): string {
        return "ALTER TABLE [{$cc['schema']}].[{$cc['table']}] WITH CHECK ADD CONSTRAINT [{$cc['name']}] CHECK {$cc['definition']};\n" .
               "ALTER TABLE [{$cc['schema']}].[{$cc['table']}] CHECK CONSTRAINT [{$cc['name']}];\nGO";
    }

    public function generateDropCheckConstraint(array $cc): string {
        return "ALTER TABLE [{$cc['schema']}].[{$cc['table']}] DROP CONSTRAINT [{$cc['name']}];\nGO";
    }

    public function generateAddDefaultConstraint(array $dc): string {
        return "ALTER TABLE [{$dc['schema']}].[{$dc['table']}] ADD CONSTRAINT [{$dc['name']}] DEFAULT {$dc['definition']} FOR [{$dc['column']}];\nGO";
    }

    public function generateDropDefaultConstraint(array $dc): string {
        return "ALTER TABLE [{$dc['schema']}].[{$dc['table']}] DROP CONSTRAINT [{$dc['name']}];\nGO";
    }

    public function generateAddIndex(array $idx): string {
        $unique = $idx['is_unique'] ? 'UNIQUE ' : '';
        $type = $idx['type'] === 'CLUSTERED' ? 'CLUSTERED ' : 'NONCLUSTERED ';
        $cols = implode(', ', array_map(fn($c) => "[$c] ASC", $idx['columns']));
        
        $sql = "CREATE {$unique}{$type}INDEX [{$idx['name']}] ON [{$idx['schema']}].[{$idx['table']}] ($cols)";
        
        if (!empty($idx['included_columns'])) {
            $inc = implode(', ', array_map(fn($c) => "[$c]", $idx['included_columns']));
            $sql .= " INCLUDE ($inc)";
        }
        
        if (!empty($idx['filter'])) {
            $sql .= " WHERE " . $idx['filter'];
        }
        
        $sql .= ";\nGO";
        return $sql;
    }

    public function generateDropIndex(array $idx): string {
        return "DROP INDEX [{$idx['name']}] ON [{$idx['schema']}].[{$idx['table']}];\nGO";
    }

    public function generateAddTrigger(array $trg): string {
        // If definition is missing (e.g. from an upload with parse errors), we output a stub
        if (empty($trg['definition'])) {
            $events = implode(' OR ', $trg['events']);
            return "CREATE TRIGGER [{$trg['schema']}].[{$trg['name']}] ON [{$trg['schema']}].[{$trg['table']}]\n" .
                   "AFTER $events\nAS\nBEGIN\n    -- Stub created because original trigger definition was missing\n    SET NOCOUNT ON;\nEND;\nGO";
        }
        return trim($trg['definition']) . "\nGO";
    }

    public function generateDropTrigger(array $trg): string {
        return "DROP TRIGGER [{$trg['schema']}].[{$trg['name']}];\nGO";
    }

    public function generateAddView(array $view): string {
        if (empty($view['definition'])) {
            return "-- WARNING: View [{$view['schema']}].[{$view['name']}] definition is encrypted or unavailable.\nGO";
        }
        return trim($view['definition']) . "\nGO";
    }

    public function generateDropView(array $view): string {
        return "DROP VIEW [{$view['schema']}].[{$view['name']}];\nGO";
    }

    public function generateAddProcedure(array $proc): string {
        if (empty($proc['definition'])) {
            return "-- WARNING: Procedure [{$proc['schema']}].[{$proc['name']}] definition is encrypted or unavailable.\nGO";
        }
        return trim($proc['definition']) . "\nGO";
    }

    public function generateDropProcedure(array $proc): string {
        return "DROP PROCEDURE [{$proc['schema']}].[{$proc['name']}];\nGO";
    }

    public function generateAddFunction(array $func): string {
        if (empty($func['definition'])) {
            return "-- WARNING: Function [{$func['schema']}].[{$func['name']}] definition is encrypted or unavailable.\nGO";
        }
        return trim($func['definition']) . "\nGO";
    }

    public function generateDropFunction(array $func): string {
        return "DROP FUNCTION [{$func['schema']}].[{$func['name']}];\nGO";
    }
}
